variables:
  BIN_NAME: "certbot.bin"
do_build:
  stage: build
  tags:
    - dev-rpmbuild
  only:
    - build
  script:
    - pushd certbot > /dev/null
    - go build -o ${BIN_NAME}
    - popd > /dev/null
  artifacts:
    paths:
      - certbot/${BIN_NAME}
    when: on_success
    expire_in: 1 day
stages:
  - build