variables:
  BIN_NAME: "certbot"
  GIT_STRATEGY: clone

do_build:
  stage: build
  image: golang
  before_script:
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  tags:
    - docker_build
  only:
    - build
  script:
    - export GOPATH=$(pwd)
    #- cat certbot/uc_accr.list
    - mkdir src build
    - mv certbot ./src/
    - pushd src/certbot > /dev/null
    - go get ./...
    - go build -o ${BIN_NAME}
    - popd > /dev/null
    - rm -rf src/certbot/parser.go
    - rsync -av  src/certbot/ build/
    #- docker-compose build && docker-compose push
    #- cat build/uc_accr.list
  artifacts:
    paths:
      - build/${BIN_NAME}
      - build/uc_accr.list
      - build/guc.list
    when: on_success
    expire_in: 1 day
  environment:
    name: m1ke
    
do_deploy:
    image: tmaier/docker-compose:18.09
    stage: deploy
    before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    tags:
     - docker_build
    only:
     - build
     script:
      - - docker-compose build && docker-compose push
stages:
  - build
  - deploy