variables:
  BIN_NAME: "certbot"
  GIT_STRATEGY: clone


do_lock:
   stage: lock
   only:
    - build
   tags:
    - golang
    - dev
   script:
    - /usr/local/bin/pipeline_lock -pipeline_id ${CI_PIPELINE_ID} -lock
    
do_unlock:
   stage: unlock
   only:
    - build
   tags:
    - golang
    - dev
   script:
    - /usr/local/bin/pipeline_lock -pipeline_id ${CI_PIPELINE_ID} -unlock 

#after_script:
#    - echo $?


do_build:
  stage: build
  tags:
    - golang
    - dev
  only:
    - build
  script:
    - export GOPATH=$(pwd)
    #- cat certbot/uc_accr.list
    - mkdir src build
    - mv certbot ./src/
    - pushd src/certbot > /dev/null
    - go get ./...
    - go build -o ${BIN_NAME}
    - popd > /dev/null
    - rm -rf src/certbot/parser.go
    - rsync -av  src/certbot/ build/
    - cat build/uc_accr.list
  artifacts:
    paths:
      - build/${BIN_NAME}
      - build/uc_accr.list
      - build/guc.list
    when: on_success
    expire_in: 1 day
  environment:
    name: m1ke

do_notify_success:
  stage: notify
  tags:
    - golang
  only:
    - build
  script:
    - curl -v  -k -i -X POST https://api.telegram.org/bot364544234:AAHryqxz5LU5w3tw6gsNlGtF8vGKzUsKFmg/sendMessage -d text="GITLAB-TEKTORG Прошла успешная сборка ${CI_PROJECT_NAME} ${CI_PROJECT_URL}" -d chat_id="-198561529" || /bin/true
  when: on_success


do_notify_failure:
  stage: notify
  tags:
    - golang
  only:
    - build
  script:
    - curl -v  -k -i -X POST https://api.telegram.org/bot364544234:AAHryqxz5LU5w3tw6gsNlGtF8vGKzUsKFmg/sendMessage -d text="GITLAB-TEKTORG Провалилась сборка для  ${CI_PROJECT_NAME} ${CI_PROJECT_URL}" -d chat_id="-198561529" || /bin/true
  when: on_failure

stages:
  - lock
  - build
  - notify
  - unlock