variables:
  BIN_NAME: "certbot"
  GIT_STRATEGY: clone

do_build:
  stage: build
  tags:
    - docker_build
  only:
    - build
  script:
    - export GOPATH=$(pwd)
    #- cat certbot/uc_accr.list
    - mkdir src build
    - mv certbot ./src/
    - pushd src/certbot > /dev/null
    - go get ./...
    - go build -o ${BIN_NAME}
    - popd > /dev/null
    - rm -rf src/certbot/parser.go
    - rsync -av  src/certbot/ build/
    - docker-compose build && docker-compose push
    #- cat build/uc_accr.list
  artifacts:
    paths:
      - build/${BIN_NAME}
      - build/uc_accr.list
      - build/guc.list
    when: on_success
    expire_in: 1 day
  environment:
    name: m1ke

stages:
  - build